-- Create the 'rooms' table to store Yjs document updates
create table if not exists rooms (
  id bigint generated by default as identity primary key,
  room_name text not null,
  document bytea not null, -- y-supabase uses bytea for storing the Y.js update
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table rooms enable row level security;

-- Create a policy that allows anyone to read/write (Public Access)
-- Note: In a production app with auth, you should restrict this.
create policy "Public Access"
on rooms
for all
using (true)
with check (true);
